#
message(STATUS "CMAKE_VERSION\t\t= ${CMAKE_VERSION}")
set(
  CMAKE_RUNTIME_OUTPUT_DIRECTORY
  ${PROJECT_SOURCE_DIR}/../bin
)
set(
  PROJECT_CONIFG_DIR
  ${PROJECT_SOURCE_DIR}/cmake/config/
)
set(
  LIB_INCLUDE_DIR
  ${PROJECT_SOURCE_DIR}/../Lib/include
)
set(
  LIB_LIB_DIR
  ${PROJECT_SOURCE_DIR}/../build/Lib
)
message(STATUS "LIB_INCLUDE_DIR = ${LIB_INCLUDE_DIR}")
message(STATUS "PROJECT_CONIFG_DIR = ${PROJECT_CONIFG_DIR}")
#