@startuml
scale 300 width
skinparam backgroundColor #FFEBDC
scale 3


package "Without Custom Config File" <<Default Style Command for Clang Format>> {
    rectangle "clang-format -style=file src/main.cxx" as c1
    cloud "clang-format -style=LLVM src/main.cxx" <<This Sytel is LLVM>> as s1

    folder p1 <<Project ONE>> [
        ----
        .cmake－format.yml
        ----
        CMakeLists.txt
        ----
        README.md
        ----
        src/main.cxx
        ----
    ]
}
c1 *-0)-> s1
c1 *--> p1

package "With Custom Config File" <<Default Style Command for Clang Format>> {
    rectangle "clang-format -style=file src/main.cxx" as c2
    cloud "clang-format -style=SYTLE src/main.cxx" <<What does the STYLE?>> as s2

    folder p2 <<Project TWO>> [
        ----
        **.clang-format**
        ----
        .cmake－format.yml
        ----
        CMakeLists.txt
        ----
        README.md
        ----
        src/main.cxx
        ----
    ]
}
c2 *-0)-> s2
c2 *--> p2



'note bottom of code
'people read the codes.
'endnote



title
    What does The Default Style of 'clang-format'?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml