@startuml
scale 400 width
skinparam backgroundColor #FFEBDC
scale 3



storage "C/C++ Code" as code
rectangle "TV" <<Device>> as tv
rectangle "PC" <<Device>> as pc
rectangle "Mobil" <<Device>> as mobil
cloud "Build Tool 'CMake'" as tools
rectangle "Windows" <<OS>> as windows
rectangle "Ubuntu" <<OS>> as ubuntu
rectangle "MacOS" <<OS>> as macos

code -(0- tv
code -(0- pc
code -(0- mobil
code -(0)- tools
code -0)- windows
code -0)- ubuntu
code -0)- macos



title
    Why does We need The 'CMake'?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml