@startuml basic_133_cmd
scale 800 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam cloud {
  backgroundColor Olive
  borderColor orange
}

left to right direction
package "build commands" <<"...">> as cmd {
    package "command for all configs" <<"dummy 2">> as ninja_1 {
        rectangle "ninja <TARGET>:all" as ninja_target_all
    }
    package "command for all default configs" <<"dummy 3">> as ninja_2 {
        rectangle "ninja <TARGET>" as ninja_default_2
    }
    package "all commands for every config" <<"dummy 5">> as ninja_3 {
        rectangle "ninja <TARGET>:Debug" as all_debug
        rectangle "ninja <TARGET>:Release" as all_release
        rectangle "ninja <TARGET>:RelWitDebInfo" as all_relwitdebinfo
        note right of all_debug
            "build/build-Debug.ninja"
        endnote
        note right of all_release
            "build/build-Release.ninja"
        endnote
        note right of all_relwitdebinfo
            "build/build-RelWitDebInfo.ninja"
        endnote
    }
    package "command for default build type" <<"dummy 4">> as ninja_4 {
        rectangle "ninja <TARGET>:<CONFIG>" as ninja_default_4
        note top of ninja_default_4
            "ninja -f build-Release.ninja <TARGET>:<CONFIG>"
        endnote
    }
    package "commands for all default configs" <<"examples 2">> as ninja_5 {
        rectangle "ninja all" as ninja_all_5
        rectangle "ninja clean" as ninja_clean_5
        note right of ninja_all_5
            all:Debug;Release
        endnote
    }
    package "commands for all configs" <<"examples 1">> as ninja_6 {
        rectangle "ninja all:all" as ninja_all_all
        rectangle "ninja clean:all" as ninja_clean_all
        note right of ninja_clean_all
            all:Debug;Release;RelWitDebInfo
        endnote
    }
}

ninja_target_all *--> ninja_all_all
ninja_target_all *--> ninja_clean_all


ninja_default_2 *--> ninja_all_5
ninja_default_2 *--> ninja_clean_5

'ninja_2 *--> ninja_3
ninja_default_2 *-(0)-> all_debug
ninja_default_2 *-(0)-> all_release
'ninja_default_2 *--> all_relwitdebinfo

'ninja_1 *--> ninja_3
ninja_target_all *--> all_debug
ninja_target_all *--> all_release
ninja_target_all *--> all_relwitdebinfo

ninja_default_4 *.(0).> all_release

title
    What is The Commands of The Ninja Multi-Config "basic_133"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml