@startuml circleci_final
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam cloud {
  backgroundColor Olive
  borderColor orange
}

left to right direction
package "C++ Project with CMake" <<"...">> as project {
  package "CMake Project" <<"CMake Code">> as cmake_project {
    rectangle "CMakeLists.txt" as cmake_code
  }
  package "CMake Generator Ninja" <<"Ninja Code">> as ninja_project {
    rectangle "cmake -GNinja -H. -B_build" <<"1. Generate Command">> as cmd_generator
    rectangle "./_build" <<Ninja Generator>> as ninja_code
    rectangle "ninja -C _build" <<"2. Build Command">> as cmd_build
    cloud "ninja -C _build zip_app" <<"3. Archiv Command">> as cmd_archiv
    cloud "**ninja -C _build github_release**" <<"4. Upload Command">> as cmd_upload
    note bottom of cmd_upload
      GITHUB_TOEKN:
        **git config --global github.token "YOUR_GITHUB_TOKEN"**
    endnote
    cmd_generator *-(0)-> ninja_code
  }
  package "C++ Project" <<"C++ Code">> as c_project {
    rectangle "main.cxx" as c_code
  }
  rectangle "Output for build" <<"./_bin">> as output_build

  cloud "Output: .tar.gz" <<"./_artifacts">> as output_artifacts
}

cloud "Output: GitHub.com" <<"./Assets">> as output_assets

cmake_code *--> ninja_project
cmd_generator *..> cmd_build
cmd_build *..> cmd_archiv
c_code *--> cmd_build
cmd_build *-(0)-> output_build
output_build *--> cmd_archiv
cmd_archiv *-(0)-> output_artifacts

output_artifacts *--> cmd_upload
cmd_archiv *..> cmd_upload
cmd_upload *-(0)-> output_assets




title
  What is The CMake's custom target `github_release` "basic_143"?
end title

header
  <font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml