@startuml circleci_final
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam cloud {
  backgroundColor Olive
  borderColor orange
}

'left to right direction
package "Local System" <<"C++ Project with CMake">> as project {
  package "CMake Project" <<"CMake Code">> as cmake_project {
    rectangle "CMakeLists.txt" as cmake_code
  }
  package "C++ Project" <<"C++ Code">> as c_project {
    rectangle "main.cxx" as c_code
  }
  cloud "config.yml" <<.circleci>> as config_yml
}

package "CircleCi" <<"Project">> as circleci {
  rectangle "Pipelines" as pipelines
  cloud "config.yml" <<.circleci>> as config_yml_circleci
}

package "GitHub" <<"Repository">> as repository {
  rectangle "main.cxx" as c_code_github
  rectangle "CMakeLists.txt" as cmake_code_github
  cloud "config.yml" <<.circleci>> as config_yml_github

  note bottom of config_yml_circleci
    <img src="./144/image/shield-passing.png">
    <img src="./144/image/shield-failing.png">
  endnote
}

project --> repository
repository .(0).> circleci
circleci .(0).> repository



title
  What is The CI Tool: CircleCi "basic_144"?
end title

header
  <font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml