@startuml destdir_final
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam cloud {
  backgroundColor Olive
  borderColor orange
}

'left to right direction
package "C++ Project with CMake" <<"...">> as project {
  package "CMake Project" <<"CMake Code">> as cmake_project {
    rectangle "CMakeLists.txt" as cmake_code
  }
  package "CMake Generator Ninja" <<"Ninja Code">> as ninja_project {
    rectangle "./_build" as ninja_code
    rectangle "ninja -C _build" <<"Build Command">> as cmd_build
    rectangle "**ninja -C _build install_app**" <<"Install Command">> as cmd_install
    note right of cmd_build
      CMake Cache Variable:
        **_DESTDIR**
        **CMAKE_BUILD_TYPE**
    endnote
    note right of cmd_install
      Environment Variable:
        **DESTDIR**
      CMake Cache Variable:
        **CMAKE_INSTALL_PREFIX**
    endnote
  }
  package "C++ Project" <<"C++ Code">> as c_project {
    rectangle "main.cxx" as c_code
  }
  rectangle "Output for build" <<"./_bin">> as output_build

  cloud "Output: Debug" <<"./_install/Debug/bin">> as output_debug
  cloud "Output: Release" <<"./_install/Release/bin">> as output_release
}
cmake_code *--> ninja_code
ninja_code *--> cmd_build
ninja_code *--> cmd_install
c_code *--> cmd_build
cmd_build *--> output_build
output_build *-(0)-> cmd_install
cmd_install *--> output_debug

cmd_install *--> output_release



title
  What is The CMake's custom target `install_app` "basic_141"?
end title

header
  <font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml