@startuml
scale 600 width
skinparam backgroundColor #FFEBDC
scale 1
skinparam backgroundColor LightYellow
skinparam state {
  BackgroundColor<<O-File>> Olive
}

[*] --> MAIN_COMPILE : BEGIN

state MAIN_COMPILE {
  state "-I./lib/header.hxx" as header_hxx_main
  header_hxx_main : "./src/main.cxx"
  state "./bin/main.cxx.o" as main_cxx_o <<O-File>>
  main_cxx_o : "OUTPUT File"

  state "./bin/main.cxx.o.d" as main_cxx_o_d <<O-File>>
  main_cxx_o_d : "OUTPUT File"

  [*] -right-> header_hxx_main : 1/2
  header_hxx_main -> main_cxx_o : "INPUT FILE"
  header_hxx_main -right-> main_cxx_o_d : "INPUT FILE"
  main_cxx_o_d -> main_cxx_o : "INPUT FILE"
}

state MAIN_LINK {
  state "./bin/main.cxx.o" as main_cxx_link
  main_cxx_link : main.cxx.o
  state "**./bin/main_112**" as main_112 <<O-File>>
  main_112 : "OUTPUT File"

  [*] -right-> main_cxx_link : 2/2
  main_cxx_o --> main_cxx_link : "INPUT FILE"
  main_cxx_link -> main_112 : link 'main.cxx'
}

title
    How to Build the State of Project "basic_112"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml