@startuml
scale 600 width
skinparam backgroundColor #FFEBDC
scale 1
skinparam backgroundColor LightYellow
skinparam state {
  BackgroundColor<<O-File>> Olive
}

[*] --> CXX_Main

state HXX_LIB {
  state "Target Library Name" as lib_111
  lib_111 : lib_111
  state "Header Directory Name" as header_dir
  header_dir : ${PROJECT_SOURCE_DIR}/include/local/

  [*] -right-> lib_111 : add_library
  lib_111 --> lib_111 : INTERFACE
  lib_111 --> header_dir : target_include_directories
  header_dir --> header_dir : INTERFACE
}

state CXX_Main {
  state "Target Executable Name" as main_111
  main_111 : main_111
  state "Source File Name" as main_cxx
  main_cxx : main.cxx

  [*] -right-> main_111
  main_111 --> main_cxx : add_executable
  main_111 --> lib_111 : target_link_libraries(main_111 lib_111)
}

state "${PROJECT_SOURCE_DIR}/include/local/" as local
local : header.hxx
header_dir --> local : Compiler
'main_cxx --> local : Compiler

state "build/rc/CMakeFiles/main_111.dir/" as o_file <<O-File>>
o_file : main.cxx.o
local -right-> o_file
CXX_Main --> o_file
'lib_111 --> main_cxx

title
    How to Build the State of Project "basic_111"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml