@startuml two_builds_130
scale 800 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam Folder {
  backgroundColor Olive
  borderColor orange
}

left to right direction
package "OUTPUT" <<./build/Lib>> as step {
    rectangle "Library Target" <<hello_lib>> as target_lib
    rectangle "Library File" <<libhello_lib.a>> as file_lib
}
package "Project 'basic_130' with Two-Builds" <<Hello, Projects!>> as basic_130_2 {
    rectangle Main_Project <<./Main>> as main_project_2
    rectangle Lib_Project <<./Lib>> as lib_project_2
    rectangle Root_Project <<./>> as root_project_2

    note left of lib_project_2
        Step 1: build
    endnote
    note left of main_project_2
        Step 2: build
    endnote
}
lib_project_2 *--> step
file_lib *.(0).> main_project_2


title
    What is The Two-Builds of Project "basic_130"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml