@startuml
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

package Project_C++ as project {
    rectangle header.hxx <<Folder: **./lib/include/**>> as header_hxx
    rectangle header.cxx <<Folder: **./lib/impl/**>> as header_cxx
    rectangle main.cxx <<Folder: ./src/>> as main
    rectangle CMakeLists.txt <<Folder: ./>> as begin
    rectangle CMakeLists.txt <<Folder: ./src/>> as src_list

    note right of begin
        add_subdirectory(lib)
        add_subdirectory(src)
    endnote
    note right of src_list
        add_executable(
            main_114
            main.cxx
            ${LIB_DIR}/impl/header.cxx
        )
        target_include_directories(
            main_114
            PRIVATE
            ${LIB_DIR}/include/
        )
    endnote
}

begin *--> src_list
src_list *-left-> header_cxx
src_list -left-> main
src_list -left-> header_hxx

title
    What is This Process's Structure of Project WITHOUT Library?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml