@startuml what-command_ubuntu
scale 600 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam Folder {
  backgroundColor Olive
  borderColor orange
}

'left to right direction
package Project_on_Ubuntu <<CMake Codes>> as project_on_ubuntu {
    rectangle add_executable <<apt_main_124, main_apt.cxx>> as apt_main_124
    rectangle add_executable <<..._main_124, ..._apt.cxx>> as main_124
    rectangle add_executable <<debconf_main_cxx, main_debconf.cxx>> as debconf_main_cxx

    rectangle include_directories <<apt_main_124, debconf_main_cxx, ...>> as include_dir
    rectangle "${_PROJECT_CONFIG_DIR}" <<...>> as _PROJECT_CONFIG_DIR
    include_dir *--> _PROJECT_CONFIG_DIR

    apt_main_124 *--> include_dir
    main_124 *--> include_dir
    debconf_main_cxx *--> include_dir
}



title
    What is This Command's Structure of Project on Ubuntu "basic_124"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml