@startuml what-hunter
scale 800 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam Folder {
  backgroundColor Olive
  borderColor orange
}

'left to right direction
package C++_SRC_DIR <<./src/>> as cxx_main {
    package target_link_libraries <<PRIVATE>> as target_link_libraries {
        rectangle target_name <<Target Executable Name>> as main_128_link
        rectangle "**lib_target_name**" <<Linking Library Name>> as lib
    }
}

package "GitHub_DIR" <<Install with FetchContent>> as github_dir {
    rectangle "./build/_deps/.../include/*.h" <<Header File>> as deps_header_file
    rectangle "./build/_deps/.../include/*.a" <<Library File>> as deps_lib_file
    deps_lib_file --> deps_header_file
}

main_128_link *--> lib
lib *.(0).> github_dir

package BREW_DIR <<Install with Brew>> as brew_dir {
    rectangle "Header File" <</usr/local/include/*.h>> as brew_usr_hxx
    rectangle "Library File" <</usr/local/lib/*.a>> as brew_usr_lib
    brew_usr_hxx --> brew_usr_lib
}

package OS_DIR <<Install with OS>> as os_dir {
    rectangle "Header File" <</usr/include/*.h>> as os_usr_hxx
    rectangle "Library File" <</usr/lib/*.a>> as os_usr_lib
    os_usr_hxx --> os_usr_lib
}

lib *.(0).> brew_dir
lib *.(0).> os_dir

Folder HUNTER_DIR <<Install with Hunter>> as hunter_dir {
    rectangle "Header File" <<$HOME/.hunter/.../include/*.h>> as hunter_hxx
    rectangle "Library File" <<$HOME/.hunter/.../lib/*.a>> as hunter_lib
    hunter_hxx --> hunter_lib
}

lib *.(0).> hunter_dir

title
    How to Link the Library For C++ Project "basic_129"?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml