@startuml
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

skinparam Folder {
  backgroundColor Olive
  borderColor orange
}

package Project_CMake as project_cmake {
    rectangle CMakeLists.txt <<Folder: ./>> as begin

    note left of begin
        add_subdirectory(cmake)
        add_subdirectory(src)
    endnote
}


package Project_C++ as project {
    rectangle main.cxx <<Folder: ./src/>> as main
    rectangle CMakeLists.txt <<Folder: ./src/>> as src_list

    note left of src_list
        add_executable(
            main_118
            main.cxx
        )
    endnote
}

package "Tool Doxygen" as Doxygen {
    rectangle CMakeLists.txt <<Folder: ./cmake/>> as cmake_list

    note right of cmake_list
        find_package(Doxygen REQUIRED)
        set(
            DOXYGEN_OUTPUT_DIRECTORY
            ${PROJECT_SOURCE_DIR}/build-docs
        )
        doxygen_add_docs(
            target_doxygen
            ${PROJECT_SOURCE_DIR}
            WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
            COMMENT "Generate html pages"
        )
    endnote
}

Folder "~~~BRIDGE~~~ FindDoxygen.cmake" {
    'CMAKE_HOME=/Applications/CMake.app/Contents/
    cloud "$CMAKE_HOME/share/cmake-3.17/Modules/FindDoxygen.cmake" <<Module>> as find_doxygen
}

package "External Software 'Doxygen'" as doxygen {
    cloud "/usr/local/bin/doxygen"
}


begin *.(0).> src_list
begin *.(0).> cmake_list
src_list -left-> main


cmake_list *--> find_doxygen
find_doxygen *-right-> doxygen


title
    What Kind of Bridge is the 'find_package' Command?
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml