@startuml what-cmake_variables
scale 700 width
skinparam backgroundColor #FFEBDC
scale 1

package "Variable Types in CMake" as types {
    rectangle "Variables in CMake" as variables
    rectangle "cmake-variables" as cmake_variables
    rectangle "Module variables" as module_variables
    rectangle "Module input variables" as input_variables
    rectangle "Module result variables" as result_variables
    rectangle "Custum variables" as custum_variables
    rectangle "internal variables" as internal_variables

    note left of cmake_variables
        PROJECT_SOURCE_DIR
    endnote
    note right of custum_variables
        _INTL_LIBRARY_DIR
    endnote
    note bottom of input_variables
        Intl_INCLUDE_DIR
        Intl_LIBRARY
    endnote
    note bottom of result_variables
        Intl_INCLUDE_DIRS
        Intl_LIBRARIES
    endnote
}

variables *--> cmake_variables
variables *--> module_variables
variables *--> custum_variables
variables *--> internal_variables
module_variables *--> input_variables
module_variables *--> result_variables

title
    What is Variable Types in CMake? "basic_123"
end title

header
<font color=red>Tips: version 1.0</font>
endheader

center footer Develop C/C++ Application with the 'CMake'

@enduml