# ./src/install.cmake
install(
  TARGETS ${TARGET_NAME}
  CONFIGURATIONS ${CMAKE_BUILD_TYPE}
  RUNTIME
    DESTINATION bin
)

message(STATUS "INSTALL_PREFIX on OS\t\t= ${CMAKE_INSTALL_PREFIX}")
message(STATUS "CMAKE_BUILD_TYPE\t\t= ${CMAKE_BUILD_TYPE}")
