# ./src/install.cmake
message(STATUS "INSTALL_PREFIX on Project\t= ${RUNTIME_INSTALL_DIRECTORY}")
message(STATUS "INSTALL_PREFIX on OS\t\t= ${CMAKE_INSTALL_PREFIX}")
install(
  TARGETS ${TARGET_NAME}
  CONFIGURATIONS Debug
  RUNTIME
    DESTINATION ${RUNTIME_INSTALL_DIRECTORY}/Debug/bin
)
install(
  TARGETS ${TARGET_NAME}
  CONFIGURATIONS Release
  RUNTIME
    DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
)