#
file(
  GENERATE OUTPUT ${PROJECT_SOURCE_DIR}/expression.md
  CONTENT "### Generator Expressions Result:
1. $<TARGET_PROPERTY:main_135,INCLUDE_DIRECTORIES>
2. $<TARGET_PROPERTY:main_135,TOOL>
3. $<BOOL:100>
4. $<BOOL:>
5. $<BOOL:$<TARGET_PROPERTY:main_135,TOOL>>
6. $<$<BOOL:100>:MACRO=100>
7. $<BOOL:$<TARGET_PROPERTY:main_135,TOOL>>:MACRO=$<TARGET_PROPERTY:main_135,TOOL>
8. $<$<BOOL:$<TARGET_PROPERTY:main_135,TOOL>>:MACRO=$<TARGET_PROPERTY:main_135,TOOL>>
"
)
#